Add Virtual Desktop + Fixe
Addition of the possibility of having a virtual desktop on wine.
Correction of a detection problem in batocera-settings
example:

batocera-settings -e -r esync -s windows -g ''
ERROR: '-g' is missing an argument.
Just type '/usr/bin/batocera-settings' to see usage page.

Added automatic detection of resolution if nothing is set.